// ReSharper disable InconsistentNaming
namespace ImoutoRebirth.BooruParser.Implementations;

// internal record DanbooruPost(
//     int id,
//     DateTimeOffset created_at,
//     int uploader_id,
//     int score,
//     string source,
//     string md5,
//     DateTimeOffset? last_comment_bumped_at,
//     string rating,
//     int image_width,
//     int image_height,
//     string tag_string,
//     int fav_count,
//     string file_ext,
//     DateTimeOffset? last_noted_at,
//     int? parent_id,
//     bool has_children,
//     int? approver_id,
//     int tag_count_general,
//     int tag_count_artist,
//     int tag_count_character,
//     int tag_count_copyright,
//     int file_size,
//     int up_score,
//     int down_score,
//     bool is_pending,
//     string is_flagged,
//     bool is_deleted,
//     int tag_count,
//     DateTimeOffset updated_at,
//     bool is_banned,
//     int pixiv_id,
//     DateTimeOffset last_commented_at,
//     bool has_active_children,
//     int bit_flags,
//     int tag_count_meta,
//     bool has_large,
//     bool has_visible_children,
//     string tag_string_general,
//     string tag_string_character,
//     string tag_string_copyright,
//     string tag_string_artist,
//     string tag_string_meta,
//     string file_url,
//     string? large_file_url,
//     string preview_file_url);
//
// internal record DanbooruNote(
//     int id,
//     DateTimeOffset created_at,
//     DateTimeOffset updated_at,
//     int x,
//     int y,
//     int width,
//     int height,
//     bool is_active,
//     int post_id,
//     string body,
//     int version);

// internal record DanbooruPool(
//     int id,
//     string name,
//     DateTimeOffset created_at,
//     DateTimeOffset updated_at,
//     string description,
//     bool is_active,
//     bool is_deleted,
//     int[] post_ids,
//     string category,
//     int post_count);
