version: 1.6.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: nuget restore Imouto.BooruParser.sln
build:
  verbosity: minimal
test_script:
- ps: dotnet test .\Imouto.BooruParser.Tests\Imouto.BooruParser.Tests.csproj --configuration Release
artifacts:
- path: Imouto.BooruParser\bin\Release\Imouto.BooruParser.*.nupkg
  name: nuget package