name: Publish nuget

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@a41619580c25efb59dfc062e92990914141abcad # v0.10.2
        with:
          versionSpec: '5.5.0'
          
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 0

      - name: Run GitVersion
        id:   gitversion
        uses: GitTools/actions/gitversion/execute@a41619580c25efb59dfc062e92990914141abcad # v0.10.2
        env:
          DOTNET_ROLL_FORWARD: Major

      - name: Echo version
        run: echo ${{ steps.gitversion.outputs.majorMinorPatch }}
      
      - name: Setup .NET Core SDK '9.x.x'
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: '9.x.x'
          include-prerelease: true

      - name: Update project version
        uses: roryprimrose/set-vs-sdk-project-version@a3f300b86a779fcdeea2c5d586ee9415c64cc42a # v1.0.6
        with:
          version: ${{ steps.gitversion.outputs.majorMinorPatch }}
  
      - name: Display dotnet version
        run: dotnet --version
          
      - name: Install Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish the package
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
