name: Publish NuGet

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
        with:
          versionSpec: '6.8.2'

      - name: Determine version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0

      - name: Setup .NET 10
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: '10.0.x'

      - name: Set project version
        uses: roryprimrose/set-vs-sdk-project-version@a3f300b86a779fcdeea2c5d586ee9415c64cc42a # v1.0.6
        with:
          version: ${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Restore
        run: dotnet restore Imouto.BooruParser.slnx

      - name: Build
        run: dotnet build Imouto.BooruParser.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test Imouto.BooruParser.slnx --configuration Release --no-build --filter "FullyQualifiedName!~FavoritePostAsyncMethod"

      - name: Pack
        run: dotnet pack Imouto.BooruParser/Imouto.BooruParser.csproj --configuration Release --no-build --output artifacts/packages

      - name: Publish package
        run: dotnet nuget push artifacts/packages/*.nupkg --api-key "${{ secrets.NUGET_ORG_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
