name: Publish Nuget

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.5.0'
      
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run GitVersion
        id:   gitversion
        uses: GitTools/actions/gitversion/execute@v0.9.11

      - name: Echo version
        run: echo ${{ steps.gitversion.outputs.majorMinorPatch }}
      
      - name: Setup .NET Core SDK '6.x.x'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x.x'

      - name: Update project version
        uses: roryprimrose/set-vs-sdk-project-version@v1
        with:
          version: ${{ steps.gitversion.outputs.majorMinorPatch }}
  
      - name: Display dotnet version
        run: dotnet --version
          
      - name: Install Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test with dotnet
        run: dotnet test --no-restore --verbosity normal --logger trx --results-directory "TestResults"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Tests            # Name of the check run which will be created
          path: TestResults/*.trx    # Path to test results
          reporter: dotnet-trx       # Format of test results

      - name: Create the package
        run: dotnet pack --configuration Release Imouto.BooruParser

      - name: Publish the package
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json
